### ISSUE TITLE
Look at compile/runtime recursions 

### ISSUE THREAD

**Issue by artemp** [mapbox/variant#3]
"...the recursion through the types in variant_helper destroy(), move(), and copy() will be done at runtime.." via @joto 

TODO

**Comment by joto** [comment]
Looking at this some more I don't see how this could be avoided. The id is only available at runtime, so we have to iterate at runtime.

**Comment by lightmare** [comment]
Agree, it's up to the compiler to optimize these. If you unwind e.g. destroy it looks like:
```c++
if (id == 3) data->~T3();
else if (id == 2) data->~T2();
else if (id == 1) data->~T1();
else data->~T0();
```
... and that should easily be turned into a switch.

**Comment by tomilov** [comment]
Surely it can be avoided in C++11: https://github.com/tomilov/variant/blob/master/include/versatile/versatile.hpp#L241

**Comment by joto** [comment]
@tomilov: interesting approach. But I am not sure it buys us anything. Yes, there is no recursion, but the price is creating this "lookup table". I guess it all depends on the code the compilers generate for the different options. Because in most cases types inside variants are probably simple types without any destructors I would expect that most of the code vanishes in the compiler in both cases. Have you looked at the generated assembler code?

**Comment by lightmare** [comment]
What I tried to convey above was that after the destroy method is recursively inlined, it becomes a cascade of if-else statements, which if the compiler is smart, can be compiled into a jump table. I haven't checked whether compilers actually do this, but if Python can do it, I'd assume others can as well.

@joto [@tomilov](https://github.com/tomilov/variant/blob/master/include/versatile/versatile.hpp#L306) optimizes the all-dtors-trivial case away with a specialization.

**Comment by tomilov** [comment]
Lookup table of function pointers is 100% C-array, whereas (just dream up) `if (...) { ... } if (...) then ...` or `switch`/`case` can turn into a number of comparisons and jumps, especially if there are skippings (due to optimized out perfectly inlined destructors for (e.g.) trivially destructible types).
