### ISSUE TITLE
Other variant implementations and the standards effort

### ISSUE THREAD

**Issue by joto** [mapbox/variant#45]
This is not the first effort to create a variant and optional type. This issue tracks other efforts and especially the standardization efforts which will probably lead to an specification for a variant type in C++17 with the goal to learn from their efforts and get our implementation to be compatible with others where possible and useful.

# Other implementations of variant and optional

* [Boost Variant](http://www.boost.org/doc/libs/1_59_0/doc/html/variant.html) and [Boost Optional](http://www.boost.org/doc/libs/1_59_0/libs/optional/doc/html/index.html)
* [Eggs Variant](http://eggs-cpp.github.io/variant/) by [Agustín Bergé](http://talesofcpp.fusionfenix.com/)
* [anthonyw/variant](https://bitbucket.org/anthonyw/variant) (implementation of P0110R0)
* [JasonL9000/cppcon14](https://github.com/JasonL9000/cppcon14)
* [tomilov/variant](https://github.com/tomilov/variant)
* [akrzemi1/Optional](https://github.com/akrzemi1/Optional)
* [mpark/variant](https://github.com/mpark/variant)

# Standards efforts

A `variant` type is on planned for inclusion in the C++ Standard, probably in C++17. Current working papers are (list extracted from [2015 working group papers](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/)):

* 2015-09-28: Variant design review. [P0086R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0086r0.pdf)
* 2015-09-28: Variant: a type-safe union without undefined behavior (v2) [P0087R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0087r0.pdf)
* 2015-09-27: Variant: a type-safe union that is rarely invalid (v5) [P0088R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0088r0.pdf)
* 2015-09-24: Simply a Strong Variant [P0093R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0093r0.html)
* 2015-09-24: Simply a Basic Variant [P0094R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0094r0.html)
* 2015-09-24: The Case for a Language Based Variant [P0096R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0095r0.html)
* 2015-09-25: Implementing the strong guarantee for variant<> assignment [P0110R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0110r0.html)
* 2015-09-24: Homogeneous interface for variant, any and optional (Revision 1) [P0032R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0032r1.pdf)

Last state can be seen from [The Variant Saga: A happy ending?](https://isocpp.org/blog/2015/11/the-variant-saga-a-happy-ending).

The `optional` type is also on the way into the standard.  The papers are:
* 2013-10-03: A proposal to add a utility class to represent optional objects (Revision 5) [N3793](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3793.html)
* 2014-01-18: Working Draft, Technical Specification on C++ Extensions for Library Fundamentals [N3848](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3848.html)

## Older Papers

* Older working drafts are: N4218 (rev 1), N4516 (rev 2), N4450 (rev 3), and [N4542](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4542.pdf) (rev 4). They have been split into P0086 (general design discussions) and P0087 and P0088 (containing two competing? specs).
* 2015-07-28: Variant: Discriminated Union with Value Semantics [P0080R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0080r0.pdf) An alternative proposal to N4542.

**Comment by lightmare** [comment]
Thanks for putting all these links together. It's been a great read, with a promising ending.

What is the fate of mapbox::variant, then? Is it going to remain "An alternative to boost::variant for C++11." // or become a stepping-stone to `std::variant` // or deemed to be replaced by one of the closer-to-std implementations before it's finalized? I'm asking because there are fundamental differences between mapbox::variant and some already-settled features of std::variant.

For example, both allow repeated types (`variant<T, T>`) but
- `std::variant` forbids using type-access `get<T>` on that, you need to use index-access, e.g. `get<0>`
- `mapbox::variant` doesn't have index-access, and allows `get<T>` in this case, picking the first `T` it finds. There's a [test case](https://github.com/mapbox/variant/blob/7883dd1cdee1650a1d8520fe64da88f4d9e7ed8c/test/t/variant.cpp#L234) suggesting that's intended, although it doesn't check duplicate types as it says it would.

Another is that `std::variant` probably won't have anything like `no_init`.

**Comment by joto** [comment]
There are no decisions yet if and how mapbox::variant will change. The collection above is meant as a basis for that decision, but there are more details we need to look at (especially current use of mapbox::variant) before we can see in what direction it should develop. I think that in the long run everybody probably wants to migrate to a std::variant, but it could be many years before that's widely available.

**Comment by springmeyer** [comment]
Voiced with @artemp and @joto on the state and future of `mapbox::variant`. Summary is:

  - `mapbox::variant` has been a very valuable, lightweight alternative for apps that do not want a boost dependency (https://github.com/mapbox/geojson-vt-cpp is recent example)
  - `mapbox::variant` has also been useful in apps that do depend on boost, like mapnik, to help (slightly) with compile times and to majorly lessen dependence on boost in core headers.
  - Original goal and near term goal is to maintain external API compatibility with `boost::variant` such that `mapbox::variant` can be a "drop in".
  - Other original goal and near term goal is to stay minimal: only implement the features that mapnik, osrm, and mapbox-gl need. So being an "incomplete" implementation is just fine.
  - We are going to defer for now on trying to be API compatible with the upcoming variant standard. Because the standard is not finished and it would be too much work. But let's revisit this in 6-8 months. It sure would be nice to eventually be able to ask `mapbox::variant` (via a DEFINE) to go into `std::variant` mode for developers that want to eventually target the standard but can't upgrade their compiler yet.

**Comment by springmeyer** [comment]
Based on ^^ I will close this issue since there is nothing actionable right now. But everyone should feel free to continue to use this issue to document ideas and findings in relation to the upcoming standard. We can re-open if any changes are actionable. Or just reference this issue in pull requests.

**Comment by joto** [comment]
I am reopening this, because I think there is a lot of valuable content here should be documented inside the repository. If it is just in a closed issue, nobody will ever find it again.

I will add some of this to README or in some doc directory or so and then close this again.
