### ISSUE TITLE
Make proper releases

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/variant#76]
The initial and also last [release](https://github.com/mapbox/variant/releases) is from April 2015. Would it be possible to tag and create stable releases? Maybe even using a semantic versioning scheme.

Use-case: we're currently using mapbox/variant in osrm-backend. We don't want to sync. with HEAD every other day, but on the other hand we're still on the April 2015 release.

**Comment by joto** [comment]
We are currently going through some rapid development and changing quite a lot of things. Once this has settled down a bit, we'll start with proper release management. In the mean time I recommend staying with the known version you have. It would also be helpful (for you and for us) if you test our master version occasionally in a branch of your code to find problems early.

**Comment by springmeyer** [comment]
I've created two new milestones that we can assign tickets to in order to get to releasing:

  - 1.1.0 - current master -> next release, mostly backwards compatible, much better tested across compilers
  - v2.0.0 - we will bump to this when we make major backwards incompatible changes like those tracked in the milestone: https://github.com/mapbox/variant/milestones/2.0.0

**Comment by springmeyer** [comment]
tracking v1.1.0 release at https://github.com/mapbox/variant/issues/78
